services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: sh ./docker/run.sh
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:16.2-alpine
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env